const ITERATION_NUMBER = 100

const POPULATION_SIZE = 100
const REPRODUCTION_SIZE = 25
const TOP_LIST_SIZE = 25

const CROSSOVER_RATE = 0.7
# MUTATION_RATE = 1 - CROSSOVER_RATE

# mutation weights
const ADD_EVENT_RATE = 2
const REMOVE_EVENT_RATE = 2
const ADD_BRANCH_OR_RATE = 3
const REMOVE_BRANCH_OR_RATE = 4
const ADD_BRANCH_AND_RATE = 2
const REMOVE_BRANCH_AND_RATE = 1
const ADD_LOOP_RATE = 0
const REMOVE_LOOP_RATE = 0

const MIN_CHROMO_SIZE = 3
const INITIAL_MAX_CHROMO_SIZE = 6

# scoring
const EVENT_PENALTY = 0.02
const EVENT_INSIDE_AND_PENALTY = 0.04
const BRANCH_PENALTY = 0.05
const LOOP_PENALTY = 0.08
const AND_PENALTY = 0.04

const LOG_FILE = "logs/example7.txt"
